alteração geral
Astroend/Albert-bot-Seguidor-de-sinais pull request #9
Opened 2022-02-16 20:59 UTC by iagobragas

atualização geral no funcionamento do Martingale, histórico, terminal, entre outros.

2022-02-16 21:31 UTC, lusqua commented on classes/action_functions.py
> +        files = filess[1]
```suggestion
        files = self.file_path[1]
```

2022-02-16 21:33 UTC, lusqua commented on classes/action_functions.py
> +    salve = Write_txt().write("boa noite")
```suggestion
    salve = Write_txt().write("boa noite")
    
```
Enter final do arquivo (boas práticas)

2022-02-16 21:42 UTC, lusqua commented on classes/api_main.py
> +                    txt = (f'''{duration} / {active} / {action} / {time} / {self.get_type} / {self.get_option} / $ {saldoo} / Martingale {trie}''')
```suggestion
                saldo = (round(float(result),2).format(saldo))
                if (trie == 0):
                    txt = (f'''{duration} / {active} / {action} / {time} / {self.get_type} / {self.get_option} / $ {saldo}''')
                else:
                    txt = (f'''{duration} / {active} / {action} / {time} / {self.get_type} / {self.get_option} / $ {saldo} / Martingale {trie}''')
```

2022-02-16 21:46 UTC, lusqua commented on classes/api_main.py
> +                Write_txt().write(txt)
Aqui não é necessário dois if, apenas um para fazer o saldo e o if serveria apenas para controlar o martingale.

2022-02-16 21:47 UTC, lusqua commented on classes/api_main.py
> +                    print("  ## Operação Salva \n")
Mesma coisa que em cima

2022-02-16 21:48 UTC, lusqua commented on classes/api_main.py
> +                print(f"  ## Oops, tive um problema em abrir a ordem {active} as {time}\n")
```suggestion
                logger.info(f"  ## Oops, tive um problema em abrir a ordem {active} as {time}\n")
```

2022-02-16 21:48 UTC, lusqua commented on classes/api_main.py
> +        print("  ## TRABALHANDO...\n")
```suggestion
        logger.info("  ## TRABALHANDO...\n")
```

2022-02-16 21:48 UTC, lusqua commented on classes/api_main.py
> +        print("\n\n  ## ...FINALIZADO\n")
```suggestion
        logger.info("\n\n  ## ...FINALIZADO\n")
```

2022-02-16 21:48 UTC, lusqua commented on main.py
> +
```suggestion
```

2022-02-16 21:49 UTC, lusqua commented on main.py
> +        print("****START****\n\n")
```suggestion
        logger.info("\n" * os.get_terminal_size().lines)
        logger.info("****START****\n\n")
```

2022-02-16 21:49 UTC, lusqua commented on main.py
> +            print(" -- CAMINHO SALVO: '" +file_historic+"'\n")
```suggestion
            logger.info(" -- CAMINHO SALVO: '" +file_historic+"'\n")
```

2022-02-16 21:49 UTC, lusqua commented on main.py
> +            print(" -- CAMINHO NÃO ENCONTRADO\n")
```suggestion
            logger.info(" -- CAMINHO NÃO ENCONTRADO\n")
```

2022-02-16 21:49 UTC, lusqua commented on main.py
> +                print("\n****EXIT****\n")
```suggestion
                logger.info("\n****EXIT****\n")
```

2022-02-16 21:50 UTC, lusqua commented on main.py
> +                print(" -- TERMOS \n")
```suggestion
                logger.info(" -- TERMOS \n")
```

2022-02-16 21:50 UTC, lusqua commented on main.py
> +                print(" -- TERMOS ACEITOS\n")
```suggestion
                logger.info(" -- TERMOS ACEITOS\n")
```

2022-02-16 21:50 UTC, lusqua commented on main.py
> +                    print(" -- WINDOW LOGIN\n")
```suggestion
                    logger.info(" -- WINDOW LOGIN\n")
```

2022-02-16 21:50 UTC, lusqua commented on main.py
> +                    print(" -- WINDOW FILE\n")
```suggestion
                    logger.info(" -- WINDOW FILE\n")
```

2022-02-16 21:50 UTC, lusqua commented on main.py
> +                print("\n****EXIT****\n")
```suggestion
                logger.info("\n****EXIT****\n")
```

2022-02-16 21:50 UTC, lusqua commented on main.py
> +                print(" -- CAMINHO ENVIADO: '" +values['file']+ "'\n")
```suggestion
                logger.info(" -- CAMINHO ENVIADO: '" +values['file']+ "'\n")
```

2022-02-16 21:51 UTC, lusqua commented on main.py
> +                    print(" -- CAMINHO SALVO\n")
```suggestion
                    logger.info(" -- CAMINHO SALVO\n")
```

2022-02-16 21:51 UTC, lusqua commented on main.py
> +                print(" -- WINDOW LOGIN\n")
```suggestion
                logger.info(" -- WINDOW LOGIN\n")
```

2022-02-16 21:51 UTC, lusqua commented on main.py
> +                print("\n****EXIT****\n")
```suggestion
                logger.info("\n****EXIT****\n")
```

2022-02-16 21:51 UTC, lusqua commented on main.py
> +                print(" -- LOGIN: {'" + values['login'] + "', '" + password +"'}\n")
```suggestion
                logger.info(" -- LOGIN: {'" + values['login'] + "', '" + password +"'}\n")
```

2022-02-16 21:51 UTC, lusqua commented on main.py
> +                    print(" -- CONECTADO \n")
```suggestion
                    logger.info(" -- CONECTADO \n")
```

2022-02-16 21:52 UTC, lusqua commented on main.py
> +                    print(" -- ERRO AO CONECTAR\n")
```suggestion
                    logger.info(" -- ERRO AO CONECTAR\n")
```

2022-02-16 21:52 UTC, lusqua commented on main.py
> +                print("\n****EXIT****\n")
```suggestion
                logger.info("\n****EXIT****\n")
```

2022-02-16 21:52 UTC, lusqua commented on main.py
> +                print(" -- SINAIS ENVIADOS\n")
```suggestion
                logger.info(" -- SINAIS ENVIADOS\n")
```

2022-02-16 21:52 UTC, lusqua commented on main.py
> +                print(" -- COMEÇANDO: {'"+str(api.get_type)+"', '"+str(api.get_balance)+"', '"+str(api.get_martingale)+"', '"
```suggestion
                logger.info(" -- COMEÇANDO: {'"+str(api.get_type)+"', '"+str(api.get_balance)+"', '"+str(api.get_martingale)+"', '"
```

2022-02-16 21:52 UTC, lusqua commented on main.py
> +                print("\n****EXIT****\n")
```suggestion
                logger.info("\n****EXIT****\n")
```

2022-02-16 21:53 UTC, lusqua commented on main.py
> +                print("\n****EXIT****\n")
```suggestion
                logger.info("\n****EXIT****\n")
```

2022-02-16 21:54 UTC, lusqua commented on classes/api_main.py
```suggestion
import logging
```

2022-02-16 21:59 UTC, lusqua commented on classes/api_main.py
colocar 
```python
logging.basicConfig(level=logging.DEBUG)
```
logo após os imports

2022-02-16 22:00 UTC, lusqua requested changes
Coloquei umas alterações que acredito que sejam interessante e deixem o código com uma manutenção mais simples.

O logging é como um print porém só aparece quando o level do debug é o mesmo das mensagens.

2022-02-16 23:12 UTC, iagobragas commented
mudanças pelo @lusqua  sugeridas aceitas

2022-02-16 23:18 UTC, lusqua commented on classes/action_functions.py
> +
```suggestion

```

2022-02-16 23:25 UTC, lusqua commented on classes/action_functions.py
> +
```suggestion
```

2022-02-16 23:37 UTC, lusqua commented on classes/api_main.py
> +                saldoo = ('{:.2f}'.format(saldo))
```suggestion
                saldo = round(float(result),2)
```

2022-02-16 23:37 UTC, lusqua commented on classes/api_main.py
> +                saldoo = ('{:.2f}'.format(saldo))
```suggestion
                saldo = round(float(result),2)
```

2022-02-17 00:02 UTC, lusqua commented on classes/action_functions.py
> +
```suggestion
```

2022-02-17 00:03 UTC, lusqua commented on classes/api_main.py
> +        Write_txt().write(txt)
```suggestion
        Write_txt().write(txt)

```

2022-02-17 00:03 UTC, lusqua commented on classes/layouts.py
> +        return sg.Window('Trading', layout=layout, finalize=True, size=(400,175),margins=(20,15,20,20))
```suggestion
        return sg.Window('Trading', layout=layout, finalize=True, size=(400,175),margins=(20,15,20,20))

```

2022-02-17 00:04 UTC, lusqua approved these changes

2022-02-17 00:05 UTC, merged